name: build eggs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - /**

jobs:
  qemu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
        - 'qbittorrent'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      -
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: Luxxy-GF
          password: ${{ secrets.REGISTRY_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/luxxy-gf/${{ matrix.tag }}
  # push:
  #   name: "luxxy-gf:${{ matrix.tag }}"
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       tag:
  #       - 'qbittorrent'
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: docker/setup-buildx-action@v1
  #       with:
  #         version: "v0.5.1"
  #         buildkitd-flags: --debug
  #     - uses: docker/login-action@v2
  #       with:
  #         registry: ghcr.io
  #         username: Luxxy-GF
  #         password: ${{ secrets.REGISTRY_TOKEN }}
  #     - uses: docker/build-push-action@v2
  #       with:
  #         context: ./
  #         file: ./${{ matrix.tag }}/Dockerfile
  #         platforms: linux/amd64
  #         push: true
  #         tags: |
  #           ghcr.io/luxxy-gf/${{ matrix.tag }}
